name: ChatQnA-test

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - ChatQnA/**
      - .github/workflows/ChatQnA.yml
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ChatQnA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ["langchain", "llamaindex"]
      fail-fast: false
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v4

      - name: Check env
        run: |
          echo y | docker system prune
          cid=$(docker ps -aq --filter "name=qna-rag-redis-server")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: backend check
        run: |
          cd ${{ github.workspace }}/ChatQnA/tests/${{ matrix.job_name }}
          bash test_${{ matrix.job_name }}_inference.sh

      - name: Publish pipeline artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job_name }}
          path: ${{ github.workspace }}/ChatQnA/tests/${{ matrix.job_name }}/*.log
